
GEMINI_API_KEY="AIzaSyAc5mjFQ4_0IYYBhz9ejTWak2G7kdP9iYA"
GOOGLE_MAPS_API_KEY="AIzaSyDhv8zr_zeynwJOSQfTDIZBJ4lW-pEcRMM"
GCP_PROJECT_ID="tonal-apex-471812-j2"
BIGQUERY_DATASET="travel_planner"
GOOGLE_APPLICATION_CREDENTIALS="/workspaces/Gen-AI-Hackathon--AI-travel-agent/service_account_key.json"